snowflake:
  database_prefix: dwh

  parameters:
    - timezone: Pacific/Auckland
    - timestamp_type_mapping: timestamp_ltz
    - require_storage_integration_for_stage_creation: true
    - quoted_identifiers_ignore_case: true
    - min_data_retention_time_in_days: 1

  warehouses:
    - dev_analyst_whs:
        size: xsmall
        auto_suspend: 60

    - dev_elt_whs:
        size: xsmall
        auto_suspend: 60

    - prd_analyst_whs:
        size: small
        auto_suspend: 60

    - prd_elt_whs:
        size: small
        auto_suspend: 60

  envs:
    - dev:
        data_retention_days: 1
    - prd:
        data_retention_days: 14
  
  layers:
    - land
    - persist
    - report
    - audit:
        env: false

  behaviour_packs:
    disable_inactive_users:
      inactive_days: 30

    log_account_usage:
      schema: audit.account_usage
  
  frameworks:
    security:
      schema: audit.security
      config_file: security.yml
      role_prefix: dwh
